import { useState, useCallback } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { 
  BookOpen, Plus, Save, Download, Trash2, Clock, 
  FlaskConical, Microscope, Atom, FileText, Pencil 
} from "lucide-react";
import { toast } from "sonner";

interface NotebookEntry {
  id: string;
  timestamp: string;
  type: 'observation' | 'hypothesis' | 'procedure' | 'result' | 'conclusion';
  content: string;
  chemicalsUsed?: string[];
  images?: string[];
}

interface LabNotebookProps {
  experimentTitle?: string;
  labType?: 'chemistry' | 'physics' | 'biology';
  autoObservations?: string[];
  onExport?: (report: string) => void;
}

const ENTRY_COLORS: Record<string, string> = {
  observation: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
  hypothesis: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
  procedure: 'bg-green-500/20 text-green-300 border-green-500/30',
  result: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
  conclusion: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
};

const ENTRY_LABELS: Record<string, string> = {
  observation: '🔍 Observation',
  hypothesis: '💡 Hypothesis',
  procedure: '📋 Procedure',
  result: '📊 Result',
  conclusion: '✅ Conclusion',
};

export function LabNotebook({ experimentTitle = "Untitled Experiment", labType = "chemistry", autoObservations = [], onExport }: LabNotebookProps) {
  const [entries, setEntries] = useState<NotebookEntry[]>([]);
  const [title, setTitle] = useState(experimentTitle);
  const [studentName, setStudentName] = useState("");
  const [newEntryType, setNewEntryType] = useState<NotebookEntry['type']>('observation');
  const [newEntryContent, setNewEntryContent] = useState("");
  const [activeTab, setActiveTab] = useState("entries");

  // Sync auto-observations
  const allEntries: NotebookEntry[] = [
    ...autoObservations.map((obs, i) => ({
      id: `auto-${i}`,
      timestamp: new Date().toLocaleTimeString(),
      type: 'observation' as const,
      content: obs,
    })),
    ...entries,
  ];

  const addEntry = useCallback(() => {
    if (!newEntryContent.trim()) {
      toast.error("Please write something first!");
      return;
    }
    const entry: NotebookEntry = {
      id: `entry-${Date.now()}`,
      timestamp: new Date().toLocaleTimeString(),
      type: newEntryType,
      content: newEntryContent.trim(),
    };
    setEntries(prev => [entry, ...prev]);
    setNewEntryContent("");
    toast.success(`${ENTRY_LABELS[newEntryType]} added!`);
  }, [newEntryContent, newEntryType]);

  const deleteEntry = useCallback((id: string) => {
    setEntries(prev => prev.filter(e => e.id !== id));
  }, []);

  const exportReport = useCallback(() => {
    const now = new Date();
    const report = `
═══════════════════════════════════════════
           LAB REPORT
═══════════════════════════════════════════

Title: ${title}
Student: ${studentName || 'N/A'}
Lab Type: ${labType.charAt(0).toUpperCase() + labType.slice(1)}
Date: ${now.toLocaleDateString()}
Time: ${now.toLocaleTimeString()}

───────────────────────────────────────────
ENTRIES
───────────────────────────────────────────

${allEntries.map(e => `[${e.timestamp}] ${ENTRY_LABELS[e.type]}
${e.content}
`).join('\n')}

───────────────────────────────────────────
Total Entries: ${allEntries.length}
Generated by Virtual Science Laboratory
═══════════════════════════════════════════
    `.trim();

    // Create downloadable file
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `lab-report-${title.replace(/\s+/g, '-').toLowerCase()}-${now.toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    onExport?.(report);
    toast.success("Lab report exported!");
  }, [title, studentName, labType, allEntries, onExport]);

  const labIcon = labType === 'chemistry' ? FlaskConical : labType === 'biology' ? Microscope : Atom;
  const LabIcon = labIcon;

  return (
    <div className="h-full flex flex-col space-y-3">
      {/* Header */}
      <Card className="bg-slate-700/50 border-slate-600">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm text-slate-200 flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-amber-400" />
            Lab Notebook
            <Badge variant="outline" className="text-xs ml-auto">
              {allEntries.length} entries
            </Badge>
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2">
          <Input
            value={title}
            onChange={e => setTitle(e.target.value)}
            placeholder="Experiment title..."
            className="bg-slate-800 border-slate-600 text-white text-sm h-8"
          />
          <Input
            value={studentName}
            onChange={e => setStudentName(e.target.value)}
            placeholder="Your name..."
            className="bg-slate-800 border-slate-600 text-white text-sm h-8"
          />
        </CardContent>
      </Card>

      <Tabs value={activeTab} onValueChange={setActiveTab} className="flex-1 flex flex-col">
        <TabsList className="grid grid-cols-2 bg-slate-700/50">
          <TabsTrigger value="entries" className="text-xs">
            <Pencil className="w-3 h-3 mr-1" />
            Write
          </TabsTrigger>
          <TabsTrigger value="log" className="text-xs">
            <FileText className="w-3 h-3 mr-1" />
            Log ({allEntries.length})
          </TabsTrigger>
        </TabsList>

        <TabsContent value="entries" className="flex-1 space-y-3 mt-2">
          {/* New Entry Form */}
          <Card className="bg-slate-700/50 border-slate-600">
            <CardContent className="pt-3 space-y-2">
              <Label className="text-xs text-slate-400">Entry Type</Label>
              <div className="flex flex-wrap gap-1">
                {Object.entries(ENTRY_LABELS).map(([key, label]) => (
                  <button
                    key={key}
                    onClick={() => setNewEntryType(key as NotebookEntry['type'])}
                    className={`text-[10px] px-2 py-1 rounded-full border transition-all ${
                      newEntryType === key
                        ? ENTRY_COLORS[key]
                        : 'border-slate-600 text-slate-400 hover:border-slate-500'
                    }`}
                  >
                    {label}
                  </button>
                ))}
              </div>
              <Textarea
                value={newEntryContent}
                onChange={e => setNewEntryContent(e.target.value)}
                placeholder={`Write your ${newEntryType}...`}
                className="bg-slate-800 border-slate-600 text-white text-xs min-h-[80px] resize-none"
              />
              <Button onClick={addEntry} size="sm" className="w-full bg-amber-600 hover:bg-amber-500 text-xs">
                <Plus className="w-3 h-3 mr-1" />
                Add Entry
              </Button>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="log" className="flex-1 overflow-y-auto mt-2">
          <div className="space-y-2">
            {allEntries.length === 0 ? (
              <p className="text-xs text-slate-500 text-center py-4 italic">
                No entries yet. Start recording your observations!
              </p>
            ) : (
              allEntries.map(entry => (
                <div
                  key={entry.id}
                  className={`text-xs p-2 rounded-lg border ${ENTRY_COLORS[entry.type]}`}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-semibold">{ENTRY_LABELS[entry.type]}</span>
                    <div className="flex items-center gap-1">
                      <Clock className="w-3 h-3" />
                      <span>{entry.timestamp}</span>
                      {!entry.id.startsWith('auto-') && (
                        <button
                          onClick={() => deleteEntry(entry.id)}
                          className="ml-1 hover:text-red-400 transition-colors"
                        >
                          <Trash2 className="w-3 h-3" />
                        </button>
                      )}
                    </div>
                  </div>
                  <p className="leading-relaxed">{entry.content}</p>
                </div>
              ))
            )}
          </div>
        </TabsContent>
      </Tabs>

      {/* Export Button */}
      <Button onClick={exportReport} variant="outline" size="sm" className="w-full border-amber-500/50 text-amber-300 hover:bg-amber-500/10 text-xs">
        <Download className="w-3 h-3 mr-1" />
        Export Lab Report
      </Button>
    </div>
  );
}
